Document: libusbx
Title: Debian libusbx Manual
Author: <insert document author here>
Abstract: This manual describes what libusbx is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libusbx/libusbx.sgml.gz

Format: postscript
Files: /usr/share/doc/libusbx/libusbx.ps.gz

Format: text
Files: /usr/share/doc/libusbx/libusbx.text.gz

Format: HTML
Index: /usr/share/doc/libusbx/html/index.html
Files: /usr/share/doc/libusbx/html/*.html
